theme: jekyll-theme-minimal

title: ðŸ§‘â€ðŸ’»ðŸ“±ðŸ‹ï¸ðŸ’¡

logo: sign.jpeg

description: Ta-Liang Lu CV

summary: >
  A versatile & 2-years working experience of back-end developer in software development industry.
  Proficient in Java & Spring, Python & Flask framework, with practical experience of integrating 3rd party APIs.
  Experienced in designing iOS App, and implementing Vue.js framework & Python connecting with MSFT & GOOG APIs. 
  Skilled in creating and troubleshooting deployments issues, and optimizing efficiency of application performance. 
